---

- hosts: local
  user: root
  tasks:
    - name: Install java and maven
      apt: pkg={{ item }} force=yes update_cache=yes
      with_items:
        - openjdk-7-jdk
        - maven
    - name: get jetty runner
      get_url: url=http://central.maven.org/maven2/org/eclipse/jetty/jetty-runner/9.2.0.RC0/jetty-runner-9.2.0.RC0.jar
               dest=/usr/local/scape/jetty-runner.jar
      # uncomment if behind a proxy (temp workaround)
      #environment:
      #  http_proxy: http://127.0.0.1:3310
    - name: create shellscript for running fcrepo.war part 1
      shell: echo '#!/bin/bash' > /usr/local/bin/run_fcrepo
    - name: create shellscript for running fcrepo.war part 2
      shell: chmod +x /usr/local/bin/run_fcrepo
    - name: create shellscript for running fcrepo.war part 3
      shell: echo 'java -jar /usr/local/scape/jetty-runner.jar /usr/local/scape/fcrepo.war' >> /usr/local/bin/run_fcrepo
